apiVersion: v1
kind: Service
metadata:
  name: hosting-reliability-service
spec:
  type: LoadBalancer
  selector:
    app: hosting-reliability-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
